segmentation:
  g_height: 1.8 # Sensor height in meters.
  g_dist_thresh: 0.2 # Distance threshold for ground-plane extraction.
  g_normal_dist_weight: 0.1 # Normal distance weight for ground-plane extraction.
  c_min_size: 100 # Min points per segment.
  c_max_size: 15000 # Max points per segment.
  c_tolerence: 0.2 # Lower values -> object becomes multiple clusters.
  ds_factor: 0.01 # Downsample voxel size. If <= 0.01, skip downsample.
  filter_flat_seg: False # Filter out flat segments.
  horizontal_ratio: 15 # Identify flat segments. Higher = flatter segment.
  enforce_min_seg_count: False # Ensure extraction of a minimum number of segments. 
  min_seg_count: 7 # Minimum number of segments (if above is True).
  visualize: True # Visualize all intermediate steps.

descriptor_generation:
  n_frames_max: 3 # Number of frames to consider in temporal pooling.
  spatial_topk: 5 # Number of neighbours to consider in spatial pooling. 
  PE_alpha: 0.5 # alpha in Power Euclidean transform.
  fb_mode: 'spatiotemporal' # Type of complementary feature in O2P. ['structural', 'spatial', 'temporal', 'spatiotemporal']

place_recognition:
  revisit_criteria: 3 # in meters.
  not_revisit_criteria: 20 # in meters.
  skip_time: 30 # in seconds.
  kdtree_retrieval: False # Use KDTree or exhaustive retrieval.
  cd_thresh_min: 0.1 # Thresholds on cosine-distance to top-1. For evaluation. 
  cd_thresh_max: 0.5
  num_thresholds: 200 # Number of thresholds. Number of points on PR curve. 

pr_curve:
  log_axis: False # See PR curve with log axis.
  introspection_table: True # See table with TP,TN,FP,FN counts at F1max and RP100.

paths:
  KITTI_dataset: '/mnt/088A6CBB8A6CA742/Datasets/Kitti/dataset/'
  save_dir: '/mnt/088A6CBB8A6CA742/locus_data/' 